ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only:[:index, :show, :create, :edit, :new, :update ]

  #   Prefix   Verb   URI Pattern                  Controller#Action
  #     cats   GET    /cats(.:format)              cats#index
  #            POST   /cats(.:format)              cats#create
  #  new_cat   GET    /cats/new(.:format)          cats#new
  # edit_cat   GET    /cats/:id/edit(.:format)     cats#edit
  #      cat   GET    /cats/:id(.:format)          cats#show
  #            PATCH  /cats/:id(.:format)          cats#update
  #            PUT    /cats/:id(.:format)          cats#update
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord

    VALID_COLORS = ['black', 'orange', 'grey', 'brindle', 'cream', 'purple', 'brown']
    VALID_SEXES = ['M', 'F']

    validates :sex, inclusion: { in: VALID_SEXES }
    validates :color, inclusion: { in: VALID_COLORS }
    validates :birth_date, :name, :color, :sex, :description, presence: true


    def age
        Date.today.year - birth_date.year
    end

end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
        # GET /cats
    def index
        @cats = Cat.all

        render :index

    end

    def show
        @cat = Cat.find(params[:id])

        render :show
    end

    def new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render @cat.errors.full_messages, status: 422
        end
    end

    def edit
        @cat = Cat.find(params[:id])

        render :edit
    end

    def update
        render json: params
    end

    private

    def cat_params
        params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
    end
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/edit.html.erb
<h3>Edit your Cat</h3>

<form action="<%= cat_url(@cat) %>" method="POST">

    <input type="hidden" name="_method" value="PATCH">

    <label for="name">Name: </label>
    <input id="name" type="text" name="cat[name]" value="<%=@cat.name%>">

    <br>
    
    <label for="birth_date">Birthdate: </label>
    <input id="birth_date" type="date" name="cat[birth_date]" value="<%=@cat.birth_date%>">

    <br>

    <label for="color">Color: </label>
    <select id="color" name="cat[color]">
        <option disabled selected>--Please Select--</option>
        <% Cat::VALID_COLORS.each do |color| %>
        <option value="<%= color %>" <%= "selected" if @cat.color == color %>>
        <%= color %></option>
        <% end %>
    </select>
    
    <br>

    <label for="M"> Male </label>
    <input type="radio" name="cat[sex]" id="M" value="M" <%= "checked" if @cat.sex == "M" %>>
    
    <label for="F"> Female </label>
    <input type="radio" name="cat[sex]" id="F" value="F" <%= "checked" if @cat.sex == "F" %>>

    <br>

    <label for="description">Description: </label>
    <textarea  id="description" name="cat[description]">
        <%= @cat.description %>    
    </textarea>

    <br>


    <input type="submit" value="Create your Kitty!">
</form>

ninety_nine_cats/app/views/cats/index.html.erb
<h1>All the Cats!</h1>

<ul>
    <% @cats.each do |cat| %>
        <li> 
            <%= cat.name %>
            <a href= "<%= cat_url(cat)%>">See Me Here </a>
        </li>
    <% end %>
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<h3>Construct a New Cat</h3>

<form action="<%= cats_url %>" method="POST">

    <label for="name">Name: </label>
    <input id="name" type="text" name="cat[name]">

    <br>
    
    <label for="birth_date">Birthdate: </label>
    <input id="birth_date" type="date" name="cat[birth_date]">

    <br>

    <label for="color">Color: </label>
    <select id="color" name="cat[color]">
        <option disabled selected>--Please Select--</option>
        <% Cat::VALID_COLORS.each do |color| %>
        <option value="<%= color %>"><%= color %></option>
        <% end %>
    </select>
    
    <br>

    <!--  <label for="sex">Sex: </label>
    <select id="sex" name="cat[sex]">
        <option disabled selected >--Please Select--</option>
         <% # Cat::VALID_SEXES.each do |sex| %>
        <option value="<%#= sex %>"><%#= sex %></option>
        <%# end %>
    </select> -->

    <label for="M"> Male </label>
    <input type="radio" name="cat[sex]" id="M" value="M">
    
    <label for="F"> Female </label>
    <input type="radio" name="cat[sex]" id="F" value="F">

    <br>

    <label for="description">Description: </label>
    <textarea  id="description" name="cat[description]"></textarea>

    <br>


    <input type="submit" value="Create your Kitty!">
</form>

ninety_nine_cats/app/views/cats/show.html.erb
<h3> Hi, I am <%= @cat.name %>! </h3>

<!-- <ul>
    <li>Birthdate : <%#= @cat.birth_date  %></li>
    <li>Color : <%#= @cat.color  %></li>
    <li>Sex : <%#= @cat.sex  %></li>
    <li>Description : <%#= @cat.description  %></li>
</ul>
-->
<table>
    <thead>
        <tr>
            <th colspan="2"> <%= @cat.name %> </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Birthdate</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>